name: Release
on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Decode Keystore
              run: |
                echo ${{ secrets.RELEASE_SIGNING_KEYSTORE }} > base64_keystore.txt
                base64 -d base64_keystore.txt > ./app/amuzic_release_keystore.jks

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Release APK
              env:
                  SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
                  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
              run: ./gradlew assembleRelease

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                 name: amuzic
                 path: ./app/build/outputs/apk/release/*.apk

            - name: Release AAB
              env:
                  SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
                  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
              run: ./gradlew bundleRelease

            - name: Upload AAB
              uses: actions/upload-artifact@v4
              with:
                  name: amuzic-bundle
                  path: ./app/build/outputs/bundle/release/*.aab

            - name: Create Release
              run: |
                gh release create ${{ github.ref_name }} --title "Amuzic $(echo ${{ github.ref_name }} | rev | cut -d 'v' -f 1 | rev)" --generate-notes
                cd ${{ github.workspace }}
                gh release upload ${{ github.ref_name }} ./app/build/outputs/apk/release/amuzic.apk ./app/build/outputs/bundle/release/amuzic.aab
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
